# Análise dos elementos de interesse no portal da Prefeitura de Caruaru


``` 
data de inicio: 2023-09-21
data de conclusão: 
```

## Obtendo dados de Obras públicas

## Páginas de interesse


|NOME|URL|IMAGEM EXEMPLO|
|----|---|-----------|
|Página inicial|https://caruaru.pe.gov.br/portal-da-transparencia/|<img src="../prefeitura_municipal/img/home_portal_transparencia_prefeitura_caruaru.png"></img>|
|Seção "Obras_Públicas"|https://caruaru.pe.gov.br/portal-da-transparencia/obras-publicas/|<img src="../prefeitura_municipal/img/secao_obras_publicas_prefeitura_caruaru.png"></img>|
|Página de buscas por Obras Públicas|https://caruaru.pe.gov.br/portal-da-transparencia/obras-publicas/|<img src="../prefeitura_municipal/img/pagina_obras_publicas_prefeitura_caruaru.png"></img>|
|Exemplo de Dados de Obras Públicas (conteúdo de um dos cards)|https://caruaru.pe.gov.br/obras/dispensa-003-2024-ct-014-2024-contratacao-direta-de-empresa-especializada-na-prestacao-dos-servicos-de-manejo-dos-residuos-solidos-urbanos-no-municipio-de-caruaru-pe/|<img src="../prefeitura_municipal/img/conteudo_detalhado_obras_prefeitura.png"></img>|

## Exploração dos elementos de interesse:

### Xpath para obter todos os links para dados de obras públicas

![xpath](../prefeitura_municipal/img/caminho_para_card_obras.png)

```
//section[@class="groupBox contrast"]/a[contains(@class, "box status")]/@href
```

In [1]:
import requests
from parsel import Selector

In [2]:
url = "https://caruaru.pe.gov.br/portal-da-transparencia/obras-publicas/"
response = requests.get(url)

In [3]:
response

In [4]:
html_text = response.text
html_selector = Selector(html_text)

urls_obras = html_selector.xpath('//section[@class="groupBox contrast"]/a[contains(@class, "box status")]/@href').getall()

urls_obras

['https://caruaru.pe.gov.br/obras/dispensa-003-2024-ct-014-2024-contratacao-direta-de-empresa-especializada-na-prestacao-dos-servicos-de-manejo-dos-residuos-solidos-urbanos-no-municipio-de-caruaru-pe/',
 'https://caruaru.pe.gov.br/obras/preg-eletr-041-2023-ct-040-2023-fornecimento-e-transporte-de-agua-bruta-com-servico-de-irrigacao-atraves-de-caminhoes-pipa-para-fins-de-irrigacao-de-pracas-parques-urbanos-jardins-canteiro/',
 'https://caruaru.pe.gov.br/obras/cp-012-2023-ct-042-2023-execucao-da-reforma-e-manutencao-dos-cemiterios-publicos-do-municipio-de-caruaru/',
 'https://caruaru.pe.gov.br/obras/cp-013-2023-ct-038-2023-execucao-de-servicos-de-conservacao-das-estradas-rurais-no-municipio-de-caruaru-pe/',
 'https://caruaru.pe.gov.br/obras/ct-150-2023-preg-eletr-008-2023-ata-reg-precos-013-2023-locacao-transporte-montagem-instalacao-e-manutencao-desmontagem-de-palco-camarote-camarim-pavilhao-arqui/',
 'https://caruaru.pe.gov.br/obras/tp-001-2023-mercado-de-carnes-2a-etapa-requalificacao/',
 'https://caruaru.pe.gov.br/obras/pe-026-2023-contratacao-de-empresa-especializada-em-locacao-de-caminhoes-guindastes-tipo-munk/',
 'https://caruaru.pe.gov.br/obras/contratacao-de-empresa-especializada-em-locacao-de-caminhoes-guindaste-tipo-munck-com-cesto-incluindo-motorista-manutencao-e-combustivel-para-apoio-as-acoes-de-poda-limpeza-e-de-manutencao-do/',
 'https://caruaru.pe.gov.br/obras/contratacao-de-empresa-especializada-em-locacao-de-caminhoes-carroceria-tipo-toco-com-operador-e-mao-de-obra-auxiliar-para-apoio-as-acoes-de-poda-e-limpeza-publica-do-municipio/',
 'https://caruaru.pe.gov.br/obras/prestacao-de-servicos-de-jardinagem-e-manutencao-de-paisagismo-nas-pracas-parques-e-canteiros-do-municipio-de-caruaru-lotes-ii-e-iii/',
 'https://caruaru.pe.gov.br/obras/locacao-instalacao-manutencao-e-limpeza-de-cabines-sanitarias-quimicas/',
 'https://caruaru.pe.gov.br/obras/contratacao-de-empresa-especializada-em-engenharia-sanitaria-para-execucao-dos-servicos-de-operacao-do-aterro-sanitario-de-residuos-solidos-urbanos-de-caruaru/',
 'https://caruaru.pe.gov.br/obras/prestacao-de-servico-de-coleta-e-transporte-de-chorume-do-aterro-sanitario-incluso-a-destinacao-final/',
 'https://caruaru.pe.gov.br/obras/sevicos-de-limpeza-desobstrucao-e-manutencao-por-viatura-de-succao-de-fossas-septicas-galerias-e-tubulacoes-de-esgotos/',
 'https://caruaru.pe.gov.br/obras/conservacao-limpeza-capinacao-desassoreamento-e-remocao-de-residuos-solidos-jogados-no-rio-ipojuca-e-nos-canais-que-desembocam-ao-longo-do-rio/',
 'https://caruaru.pe.gov.br/obras/locacao-montagem-e-desmontagem-e-manutencao-de-estruturas-e-equipamentos/',
 'https://caruaru.pe.gov.br/obras/prestacao-de-servico-de-remocao-e-transporte-de-residuos-da-construcao-civil/',
 'https://caruaru.pe.gov.br/obras/contratacao-de-empresa-especializada-na-locacao-instalacao-manutencao-e-limpeza-de-cabines-sanitarias-quimicas/',
 'https://caruaru.pe.gov.br/obras/execucao-dos-servicos-de-limpeza-urbana/',
 'https://caruaru.pe.gov.br/obras/cp-004-2023-ct-023-2023-implantacao-de-bueiros-nas-estradas-rurais-do-municipio-de-caruaru-pe/',
 'https://caruaru.pe.gov.br/obras/cp-026-2023-ct-004-2024-execucao-dos-servicos-de-recapeamento-e-drenagem-na-central-de-abastecimento-de-caruaru-ceaca-em-caruaru-pe/',
 'https://caruaru.pe.gov.br/obras/cp-024-2023-contrato-0006-2024-execucao-do-recapeamento-asfaltico-e-drenagem-em-diversas-ruas-nos-bairros-indianopolis-e-deputado-jose-antonio-liberato/',
 'https://caruaru.pe.gov.br/obras/conclusao-da-obra-de-requalificacao-do-patio-da-antiga-estacao-ferroviaria-de-caruaru-pe/',
 'https://caruaru.pe.gov.br/obras/revitalizacao-do-parque-da-lagoa-no-municipio-de-caruaru-pe-2/']

## Obtendo dados das Obras

In [5]:
obras_page = requests.get(urls_obras[0])

In [6]:
obras_page_text = obras_page.text
obras_selector = Selector(obras_page_text)
# Obtem todas as categorias (chaves principais) do formulário
keys = obras_selector.xpath('//section[@class="description-obra"]//div[@class="group-title"]/text()').getall()

keys

['MODALIDADE | Nº DA LICITAÇÃO',
 'DESCRIÇÃO DA OBRA',
 'CONVÊNIO',
 'CONTRATADO',
 'CONTRATO',
 'ADITIVO',
 'DESPESAS DO EXERCÍCIO',
 'VALOR PAGO ACUMULADO',
 'SITUAÇÃO',
 'ETAPA DA OBRA',
 'PERCENTUAL CONCLUÍDO',
 'TODOS OS DOCUMENTOS']

In [7]:
# Obtem todas as subcategorias (chaves aninhadas) do formulário
nested_keys = obras_selector.xpath('//div[@class="row-cards"]/div[@class="row-card"]/div[@class="card-title"]/text()').getall()
# Associa as subcategorias com sua respectiva categoria 
nested_keys

['Nº',
 'Concedente',
 'CPF | CNPJ',
 'Razão Social',
 'Nº',
 'Data ínicio',
 'Prazo',
 'Valor Contratado (R$)',
 'Data Conclusão / Paralisação',
 'Prazo Aditado',
 'Valor Aditado Acumulado (R$)',
 'Valor Médio Acumulado (R$)',
 'Valor pago Acumulado no período (R$)',
 'Valor pago Acumulado no exercício (R$)']

In [8]:
# Obtendo os valores das chaves e chaves aninhadas
retrive_values = obras_selector.xpath('//section[@class="description-obra"]/div[@class="row-details"]//div[@class="card-info"]/text()[normalize-space()]').getall()

retrive_values

['\n                                    DISPENSA 003/2024                                 \n                                ',
 'DISPENSA 003/2024 - CT 014/2024 - CONTRATAÇÃO DIRETA DE EMPRESA ESPECIALIZADA NA PRESTAÇÃO DOS SERVIÇOS DE MANEJO DOS RESÍDUOS SÓLIDOS URBANOS NO MUNICÍPIO DE CARUARU-PE',
 '\n                                            -',
 '\n                                            -',
 '\n                                            35.474.949/0001-08',
 '\n                                            LOCAR SANEAMENTO AMBIENTAL LTDA',
 '\n                                            014/2024',
 '\n                                            03/04/2024',
 '\n                                            12 MESES ',
 '\n                                            R$ 48.396.075,12',
 '-',
 '\n                                            -',
 '\n                                            R$ 48.396.075,12',
 '\n                                            R$ 3.374.463,60 ',
 '\n                                            R$ 772.033,10 ',
 '\n                                            R$ 772.033,10 ',
 '\n                                    R$ 772.033,10 ',
 '\n                                    em Andamento                                ',
 '\n                                        SERVIÇO CONTÍNUO                                    ',
 '\n                                        1.60%                                    ']

In [9]:
import re

value_list = []

for value in retrive_values:
    formated_item = re.sub(r"\s+", " ", value).strip()
    value_list.append(formated_item)

value_list

['DISPENSA 003/2024',
 'DISPENSA 003/2024 - CT 014/2024 - CONTRATAÇÃO DIRETA DE EMPRESA ESPECIALIZADA NA PRESTAÇÃO DOS SERVIÇOS DE MANEJO DOS RESÍDUOS SÓLIDOS URBANOS NO MUNICÍPIO DE CARUARU-PE',
 '-',
 '-',
 '35.474.949/0001-08',
 'LOCAR SANEAMENTO AMBIENTAL LTDA',
 '014/2024',
 '03/04/2024',
 '12 MESES',
 'R$ 48.396.075,12',
 '-',
 '-',
 'R$ 48.396.075,12',
 'R$ 3.374.463,60',
 'R$ 772.033,10',
 'R$ 772.033,10',
 'R$ 772.033,10',
 'em Andamento',
 'SERVIÇO CONTÍNUO',
 '1.60%']

In [10]:
# Restrutua do formulário
form_structure = {
    keys[0]: value_list[0],
    keys[1]: value_list[1],
    keys[2]: {
        nested_keys[0]: value_list[2],
        nested_keys[1]: value_list[3],
    },
    keys[3]:{
        nested_keys[2]: value_list[4],
        nested_keys[3]: value_list[5],
    },
    keys[4]: {
        nested_keys[4]: value_list[6],
        nested_keys[5]: value_list[7],
        nested_keys[6]: value_list[8],
        nested_keys[7]: value_list[9],
        nested_keys[8]: value_list[10],
    },
    keys[5]: {
        nested_keys[9]: value_list[11],
        nested_keys[10]:value_list[12],
    },
    keys[6]: {
        nested_keys[11]:value_list[13],
        nested_keys[12]:value_list[14],
        nested_keys[13]:value_list[15],
    },
    keys[7]:value_list[16],
    keys[8]:value_list[17],
    keys[9]:value_list[18],
    keys[10]:value_list[19],
}

form_structure

{'MODALIDADE | Nº DA LICITAÇÃO': 'DISPENSA 003/2024',
 'DESCRIÇÃO DA OBRA': 'DISPENSA 003/2024 - CT 014/2024 - CONTRATAÇÃO DIRETA DE EMPRESA ESPECIALIZADA NA PRESTAÇÃO DOS SERVIÇOS DE MANEJO DOS RESÍDUOS SÓLIDOS URBANOS NO MUNICÍPIO DE CARUARU-PE',
 'CONVÊNIO': {'Nº': '-', 'Concedente': '-'},
 'CONTRATADO': {'CPF | CNPJ': '35.474.949/0001-08',
  'Razão Social': 'LOCAR SANEAMENTO AMBIENTAL LTDA'},
 'CONTRATO': {'Nº': '014/2024',
  'Data ínicio': '03/04/2024',
  'Prazo': '12 MESES',
  'Valor Contratado (R$)': 'R$ 48.396.075,12',
  'Data Conclusão / Paralisação': '-'},
 'ADITIVO': {'Prazo Aditado': '-',
  'Valor Aditado Acumulado (R$)': 'R$ 48.396.075,12'},
 'DESPESAS DO EXERCÍCIO': {'Valor Médio Acumulado (R$)': 'R$ 3.374.463,60',
  'Valor pago Acumulado no período (R$)': 'R$ 772.033,10',
  'Valor pago Acumulado no exercício (R$)': 'R$ 772.033,10'},
 'VALOR PAGO ACUMULADO': 'R$ 772.033,10',
 'SITUAÇÃO': 'em Andamento',
 'ETAPA DA OBRA': 'SERVIÇO CONTÍNUO',
 'PERCENTUAL CONCLUÍDO': '1.60%'}

## Obtendo os documentos referentes aos contratos e a localização da obra

In [11]:
docs = obras_selector.xpath('//div[@class="card-info card-info--docs"]/div[@class="attachment"]//p[@class="cardTitle"]/text()').getall()
docs

[' Termo de Referência ', ' Contrato 014/2024 ', '  ']

In [12]:
docs_links = obras_selector.xpath('//div[@class="card-info card-info--docs"]/div[@class="attachment"]//div[@class="button"]/a/@href').getall()
docs_links

['https://caruaru.pe.gov.br/wp-content/uploads/2024/09/08plhst34IoG_Termo-de-referencia.pdf',
 'https://caruaru.pe.gov.br/wp-content/uploads/2024/09/Q7DEzPXQmXm7_CONTRATO-No-014.2024-DISPENSA-003.2024-LOCAR.pdf',
 '']

In [13]:
documents = {
    keys[11]: {
        docs[0].strip(): docs_links[0].strip(),
        docs[1].strip(): docs_links[1].strip(),
        
    }
}

documents

{'TODOS OS DOCUMENTOS': {'Termo de Referência': 'https://caruaru.pe.gov.br/wp-content/uploads/2024/09/08plhst34IoG_Termo-de-referencia.pdf',
  'Contrato 014/2024': 'https://caruaru.pe.gov.br/wp-content/uploads/2024/09/Q7DEzPXQmXm7_CONTRATO-No-014.2024-DISPENSA-003.2024-LOCAR.pdf'}}

## Obtendo as coordenadas de longitude e latitude do local em que a obra foi realizada

In [14]:
map_obra_key = obras_selector.xpath('//section[@class="map-obra"]//div[@class="map-obra_title"]/p/text()').get()
map_obra_key

'Localização da Obra'

In [15]:
map_obra_values = obras_selector.xpath('//section[@class="map-obra"]//iframe/@src').getall()
map_obra_values

[]

In [16]:
# Extraindo a longitude e latitude do iframe
for iframe_src in map_obra_values:

    pattern = r'2d(-?\d+\.\d+)!3d(-?\d+\.\d+)'
    match = re.search(pattern, iframe_src)

    if match:
        longitude = match.group(1)
        latitude = match.group(2)
        print(f"Latitude: {latitude}, Longitude: {longitude}")

## Script completo

In [18]:
import re
import requests
from parsel import Selector

url = "https://caruaru.pe.gov.br/portal-da-transparencia/obras-publicas/"
response = requests.get(url)
html_text = response.text
html_selector = Selector(html_text)

urls_obras = html_selector.xpath('//section[@class="groupBox contrast"]/a[contains(@class, "box status")]/@href').getall()
# Seleciona uma obra como exemplo para extração dos dados
obras_page = requests.get(urls_obras[0])
obras_page_text = obras_page.text
obras_selector = Selector(obras_page_text)
# Obtem todas as categorias (chaves principais) do formulário
keys = obras_selector.xpath('//section[@class="description-obra"]//div[@class="group-title"]/text()').getall()
# Obtem todas as subcategorias (chaves aninhadas) do formulário
nested_keys = obras_selector.xpath('//div[@class="row-cards"]/div[@class="row-card"]/div[@class="card-title"]/text()').getall()
# Obtendo os valores das chaves e chaves aninhadas
retrive_values = obras_selector.xpath('//section[@class="description-obra"]/div[@class="row-details"]//div[@class="card-info"]/text()[normalize-space()]').getall()

value_list = []

for value in retrive_values:
    formated_item = re.sub(r"\s+", " ", value).strip()
    value_list.append(formated_item)

docs = obras_selector.xpath('//div[@class="card-info card-info--docs"]/div[@class="attachment"]//p[@class="cardTitle"]/text()').getall()
docs_links = obras_selector.xpath('//div[@class="card-info card-info--docs"]/div[@class="attachment"]//div[@class="button"]/a/@href').getall()
map_obra_key = obras_selector.xpath('//section[@class="map-obra"]//div[@class="map-obra_title"]/p/text()').get()
map_obra_values = obras_selector.xpath('//section[@class="map-obra"]//iframe/@src').getall()
coordinates = []

# Extraindo a longitude e latitude do iframe
for iframe_src in map_obra_values:

    pattern = r'2d(-?\d+\.\d+)!3d(-?\d+\.\d+)'
    match = re.search(pattern, iframe_src)

    if match:
        longitude = match.group(1)
        latitude = match.group(2)
        coordinates.append({"Latitude": latitude, "Longitude": longitude} )

if not coordinates:
    coordinates = None

# Formulário completo
form_structure = {
    keys[0]: value_list[0],
    keys[1]: value_list[1],
    keys[2]: {
        nested_keys[0]: value_list[2],
        nested_keys[1]: value_list[3],
    },
    keys[3]:{
        nested_keys[2]: value_list[4],
        nested_keys[3]: value_list[5],
    },
    keys[4]: {
        nested_keys[4]: value_list[6],
        nested_keys[5]: value_list[7],
        nested_keys[6]: value_list[8],
        nested_keys[7]: value_list[9],
        nested_keys[8]: value_list[10],
    },
    keys[5]: {
        nested_keys[9]: value_list[11],
        nested_keys[10]:value_list[12],
    },
    keys[6]: {
        nested_keys[11]:value_list[13],
        nested_keys[12]:value_list[14],
        nested_keys[13]:value_list[15],
    },
    keys[7]:value_list[16],
    keys[8]:value_list[17],
    keys[9]:value_list[18],
    keys[10]:value_list[19],
    keys[11]: {
        docs[0].strip(): docs_links[0].strip(),
        docs[1].strip(): docs_links[1].strip(),
    },
    "GEO COORDENADAS DA OBRA": coordinates,
}

form_structure

{'MODALIDADE | Nº DA LICITAÇÃO': 'DISPENSA 003/2024',
 'DESCRIÇÃO DA OBRA': 'DISPENSA 003/2024 - CT 014/2024 - CONTRATAÇÃO DIRETA DE EMPRESA ESPECIALIZADA NA PRESTAÇÃO DOS SERVIÇOS DE MANEJO DOS RESÍDUOS SÓLIDOS URBANOS NO MUNICÍPIO DE CARUARU-PE',
 'CONVÊNIO': {'Nº': '-', 'Concedente': '-'},
 'CONTRATADO': {'CPF | CNPJ': '35.474.949/0001-08',
  'Razão Social': 'LOCAR SANEAMENTO AMBIENTAL LTDA'},
 'CONTRATO': {'Nº': '014/2024',
  'Data ínicio': '03/04/2024',
  'Prazo': '12 MESES',
  'Valor Contratado (R$)': 'R$ 48.396.075,12',
  'Data Conclusão / Paralisação': '-'},
 'ADITIVO': {'Prazo Aditado': '-',
  'Valor Aditado Acumulado (R$)': 'R$ 48.396.075,12'},
 'DESPESAS DO EXERCÍCIO': {'Valor Médio Acumulado (R$)': 'R$ 3.374.463,60',
  'Valor pago Acumulado no período (R$)': 'R$ 772.033,10',
  'Valor pago Acumulado no exercício (R$)': 'R$ 772.033,10'},
 'VALOR PAGO ACUMULADO': 'R$ 772.033,10',
 'SITUAÇÃO': 'em Andamento',
 'ETAPA DA OBRA': 'SERVIÇO CONTÍNUO',
 'PERCENTUAL CONCLUÍDO': '1.60%',
 'TODOS OS DOCUMENTOS': {'Termo de Referência': 'https://caruaru.pe.gov.br/wp-content/uploads/2024/09/08plhst34IoG_Termo-de-referencia.pdf',
  'Contrato 014/2024': 'https://caruaru.pe.gov.br/wp-content/uploads/2024/09/Q7DEzPXQmXm7_CONTRATO-No-014.2024-DISPENSA-003.2024-LOCAR.pdf'},
 'GEO COORDENADAS DA OBRA': None}

In [9]:
import pandas as pd
import json

In [11]:
path = "/home/tiago/Workspace/projetos/mutuca/public_works_cityhall.json"

with open(path, "r") as f:
    data = json.load(f)

df = pd.json_normalize(data)

df.head()

,modality_bidding_number,project_description,total_paid_amount,status,project_stage,completion_percentage,geo_coordinates,agreement.Nº,agreement.Concedente,contracted.CPF | CNPJ,...,all_documents. Anexo B - Composição BDI,all_documents. Anexo B - Composição de BDI's,all_documents. Anexo D - Composicoes,all_documents. Anexo C - Planilha,all_documents. BDI,all_documents. Anexo D - Composições de Preço Unitário,all_documents. Anexo B – Composição de BDI,all_documents. Anexo J - Licença Ambiental 1,all_documents. Anexo J - Licença Ambiental 2,all_documents. CV 011/2016 - CONSTRUÇÃO DO CREAS - CEDRO
0,CONCORRÊNCIA PÚBLICA Nº 012/2023,CP 012/2023 - CT 042/2023 - Execução da Reform...,"0,0",em Andamento,SERVIÇO DE MANUTENÇÃO,0.0%,[],-,-,47.255.285/0001-75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CONCORRÊNCIA PÚBLICA 0009/2017,CONTRATAÇÃO DE EMPRESA ESPECIALIZADA EM ENGENH...,"R$ 7.048.346,62",em Andamento,SERVIÇO CONTÍNUO,35.73%,[https://www.google.com/maps/d/u/1/embed?mid=1...,-,-,15.121.099/0001-57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,PREGÃO PRESENCIAL 0037/2019,PP 0037/2019 - CT 073/2019 - SEVIÇOS DE LIMPEZ...,"R$ 365.842,80",em Andamento,SERVIÇO CONTÍNUO,66.14%,[https://www.google.com/maps/d/u/1/embed?mid=1...,-,-,03.859.984/0001-59,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,PREGÃO PRESENCIAL 0023/2018,PRESTAÇÃO DE SERVIÇO DE COLETA E TRANSPORTE DE...,"R$ 2.720.522,20",em Andamento,SERVIÇO CONTÍNUO,74.84%,[https://www.google.com/maps/d/u/1/embed?mid=1...,-,-,03.859.984/0001-59,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ATA DE REGISTRO DE PREÇOS 055/2021 PREGÃO ELET...,"LOCAÇÃO, INSTALAÇÃO, MANUTENÇÃO E LIMPEZA DE C...","R$ 50.340,00",em Andamento,SERVIÇO CONTÍNUO,27.89%,[https://www.google.com/maps/d/u/1/embed?mid=1...,-,-,03.859.984/0001-59,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.describe()

,modality_bidding_number,project_description,agreement,contracted,contract,amendment,expenses,total_paid_amount,status,project_stage,completion_percentage,all_documents,geo_coordinates
count,414,414,414,414,414,414,414,414,414,413,395,118,414
unique,274,389,98,154,407,330,390,348,98,89,124,118,245
top,CP 021/2021,CONTRATAÇÃO DE EMPRESA ESPECIALIZADA NA EXECUÇ...,"{'Nº': '-', 'Concedente': '-'}","{'CPF | CNPJ': '26.725.233/0001-45', 'Razão So...","{'Nº': '011/2019', 'Data ínicio': '27/03/2019'...","{'Prazo Aditado': '-', 'Valor Aditado Acumulad...","{'Valor Médio Acumulado (R$)': '0,00', 'Valor ...",-,Concluída,Finalizada,100%,{' Contrato ': 'https://caruaru.pe.gov.br/wp-c...,[]
freq,13,7,77,23,2,77,16,33,214,117,178,1,36